{{- $global := .Values.global | default dict }}
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: K0sControlPlane
metadata:
  name: {{ include "k0scontrolplane.name" . }}
  namespace: {{ .Values.cluster.namespace | default .Release.Namespace | trunc 63 }}
spec:
  replicas: {{ .Values.controlPlaneNumber }}
  version: {{ .Values.k0s.version }}
  k0sConfigSpec:
    {{- if $global.k0sURL }}
    downloadURL: "{{ $global.k0sURL }}/k0s-{{ .Values.k0s.version }}-amd64"
    {{- end }}
    args:
      - --enable-worker
      - --enable-cloud-provider
      - --kubelet-extra-args="--cloud-provider=external"
      - --disable-components=konnectivity-server
    files:
    {{- if .Values.controlPlane.files }}
      {{- toYaml .Values.controlPlane.files | nindent 6 }}
    {{- end }}
    {{- if or $global.registryCertSecret $global.k0sURLCertSecret }}
    {{- $certs := dict "registry.crt" $global.registryCertSecret "k0s-url.crt" $global.k0sURLCertSecret }}
      {{- range $path, $secret := $certs }}
      {{- if $secret }}
      - contentFrom:
          secretRef:
            name: {{ $secret }}
            key: tls.crt
        permissions: "0664"
        path: /usr/local/share/ca-certificates/{{ $path }}
      {{- end }}
      {{- end }}
    {{- end }}
    preStartCommands:
    {{- with .Values.controlPlane.preStartCommands }}
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- if or $global.registryCertSecret $global.k0sURLCertSecret }}
      - sudo update-ca-certificates
    {{- end }}
    k0s:
      apiVersion: k0s.k0sproject.io/v1beta1
      kind: ClusterConfig
      metadata:
        name: k0s
      spec:
        api:
          extraArgs:
            anonymous-auth: "true"
            {{- with .Values.k0s.api.extraArgs }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
        network:
          podCIDR: {{ index .Values.clusterNetwork.pods.cidrBlocks 0 }}
          serviceCIDR: {{ index .Values.clusterNetwork.services.cidrBlocks 0 }}
          provider: calico
          calico:
            mode: vxlan
            vxlanPort: {{ .Values.k0s.network.vxlanPort }}
            envVars:
              CALICO_IPV4POOL_CIDR: "{{ index .Values.clusterNetwork.pods.cidrBlocks 0 }}"
              CLUSTER_TYPE: "k8s"
              CALICO_IPV4POOL_IPIP: "Never"
              CALICO_IPV4POOL_VXLAN: "Always"
              FELIX_VXLANPORT: "{{ .Values.k0s.network.vxlanPort }}"
              FELIX_ALLOWVXLANPACKETSFROMWORKLOADS: "true"
        {{- if $global.registry }}
        images:
          metricsserver:
            image: "{{ $global.registry}}/metrics-server/metrics-server"
          kubeproxy:
            image: "{{ $global.registry}}/k0sproject/kube-proxy"
          coredns:
            image: "{{ $global.registry}}/k0sproject/coredns"
          pause:
            image: "{{ $global.registry}}/pause"
          calico:
            cni:
              image: "{{ $global.registry}}/k0sproject/calico-cni"
            node:
              image: "{{ $global.registry}}/k0sproject/calico-node"
            kubecontrollers:
              image: "{{ $global.registry}}/k0sproject/calico-kube-controllers"
        {{- end }}
        extensions:
          helm:
            charts:
            - name: kubernetes-csi-external-snapshotter
              {{- if $global.registry }}
              chartname: oci://{{ $global.registry }}/k0rdent-oot/oot/charts/kubernetes-csi-external-snapshotter
              {{- else }}
              chartname: oci://ghcr.io/k0rdent-oot/oot/charts/kubernetes-csi-external-snapshotter
              {{- end }}
              version: v8.2.0
              order: 1
              namespace: kube-system
              {{- if $global.registry }}
              values: |
                image:
                  repository: {{ $global.registry }}/sig-storage/snapshot-controller
              {{- end }}
            - name: kubevirt-csi-driver-tenant
              {{- if $global.registry }}
              chartname: oci://{{ $global.registry }}/k0rdent-oot/oot/charts/kubevirt-csi-driver-tenant
              {{- else }}
              chartname: oci://ghcr.io/k0rdent-oot/oot/charts/kubevirt-csi-driver-tenant
              {{- end }}
              version: 0.1.0
              order: 2
              namespace: kube-system
              values: |
                infraClusterNamespace: {{ .Values.cluster.namespace | default .Release.Namespace | trunc 63 }}
                infraClusterLabels: csi-driver/cluster={{ .Release.Name }}
                infraStorageClassName: {{ .Values.kubevirtCsiDriver.infraStorageClassName }}
              {{- if $global.registry }}
                csiDriver:
                  repo: {{ $global.registry }}/kubevirt
                csiNodeDriverRegistrar:
                  repo: {{ $global.registry }}/sig-storage
                csiLivenessProbe:
                  repo: {{ $global.registry }}/sig-storage
              {{- end }}
  machineTemplate:
    infrastructureRef:
      apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
      kind: KubevirtMachineTemplate
      name: {{ include "kubevirtmachinetemplate.controlplane.name" . }}
      namespace: {{ .Values.cluster.namespace | default .Release.Namespace | trunc 63 }}
